// <auto-generated />
using System;
using Cofrinho.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cofrinho.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CofrinhoDbContext))]
    [Migration("20260107231253_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Cofrinho.Domain.Entities.Meta", b =>
                {
                    b.Property<string>("Nome")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.HasKey("Nome");

                    b.ToTable("metas", (string)null);
                });

            modelBuilder.Entity("Cofrinho.Domain.Entities.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<string>("MetaNome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.Property<string>("meta_nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("meta_nome");

                    b.HasKey("Id");

                    b.HasIndex("MetaNome");

                    b.HasIndex("meta_nome");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("Cofrinho.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("Cofrinho.Domain.Entities.Meta", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("MetaNome");

                    b.HasOne("Cofrinho.Domain.Entities.Meta", null)
                        .WithMany("_transacoes")
                        .HasForeignKey("meta_nome")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cofrinho.Domain.Entities.Meta", b =>
                {
                    b.Navigation("Transacoes");

                    b.Navigation("_transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
